Changes to accomodate new SKA runtime environment (skare):
Makefile.in
  - Remove refs to standalone starcheck
  - Add installation of starcheck launcher
  - Run regression using starcheck in dev install not src
starcheck.pl  Launch with /proj/sot/ska/bin/perl instead of perlska
  - Check for undef row in parsed table before printing
standalone_regress
  - Delete file
run_regress
  - Refactor to call a subroutine for each test case
  - Run the dev install via starcheck launcher
starcheck
  - New standalone starcheck launcher (activates SKA runtime environment)
Obsid.pm
  - Explicitly specify package for toAngle() conversion

diff --git a/src/run_regress b/src/run_regress
--- a/src/run_regress
+++ b/src/run_regress
@@ -1,6 +1,66 @@
 #! /bin/sh
 
-# Regression tests for starcheck
+# Comprehensive regression tests for starcheck
+
+RunRegression()
+# Run regression tests.
+# Arg 1 is the AGASC version (e.g. 1p5)
+# Arg 2 is the fid characteristics name (e.g. fid_CHARACTERIS_FEB07)
+{
+  echo ""
+  echo "***** Running starcheck on load $load *****"
+
+  agasc=${1}
+  fid_char=${2}
+
+  test=$home/regress/test/$load
+  release=$home/regress/release/$load
+
+  # Make sure we have a clean test directory
+  if [ -d $test ]
+  then
+    echo "rm -r $test"
+    rm -r $test
+  fi
+
+  echo "mkdir -p $test"
+  mkdir -p $test
+
+  echo "cd $test"
+  cd $test
+
+  # Run test version.  Use the 'starcheck' launcher to activate the dev environment
+  #
+  echo "Running: $SKA/bin/starcheck -agasc $agasc -fid_char $fid_char -dir $mphome/$load"
+  echo "******************** (TEST) $load *******************" >> $log
+  $SKA/bin/starcheck -agasc $agasc -fid_char $fid_char -dir $mphome/$load 2>&1| tee -a $log
+  perl -p -i.bak -e "s{$SKA}{$RELEASE}" $test/starcheck.txt
+
+  # Now run current release version if not already there
+  #
+  if [ ! -r $release/starcheck.txt ]
+  then
+    echo "mkdir -p $release"
+    mkdir -p $release
+
+    echo "cd $release"
+    cd $release
+
+    echo "Running: $RELEASE/bin/starcheck.pl -agasc $agasc -fid_char $fid_char -dir $mphome/$load"
+    echo "**** (RELEASE) $load ****" >> $log
+    env SKA=$RELEASE PERL5LIB='' SYBASE='' $RELEASE/bin/starcheck.pl -agasc $agasc -fid_char $fid_char -dir $mphome/$load 2>&1| tee -a $log
+  fi  
+
+
+  # Now compare with release version
+
+  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
+  echo "********************* $load ********************" >> $diffs
+  diff $test/starcheck.txt $release/starcheck.txt >> $diffs
+
+  cd $home
+}
+                                                                                                                                                             
 
 # Define the files and directories
 home=$PWD
@@ -8,10 +68,12 @@ mphome=/data/mpcrit1/mplogs
 log=$home/regress_log
 diffs=$home/regress_diffs
 
-TESTING_BIN=$PWD/src
+RELEASE=/proj/sot/ska
 
-# Change this to /proj/sot/ska/bin after next release
-RELEASE_BIN=/proj/sot/ska/bin/  
+if [ "$SKA" = "$RELEASE" ] ; then
+  echo "Error - test bin is the same as the release bin."
+  exit 1
+fi
 
 # Remove existing log and diffs files
 for file in $log $diffs
@@ -42,53 +104,8 @@ for load in \
     2004/MAY3104/oflsc \
     2004/JUL2604/oflsa \
     2004/DEC2704/oflsb 
-  do
-  echo ""
-  echo "***** Running starcheck on load $load *****"
-  
-  test=$home/regress/test/$load
-  release=$home/regress/release/$load
-
-  # Make sure we have a clean test directory
-  if [ -d $test ]
-  then
-    echo "rm -r $test"
-    rm -r $test
-  fi
-
-  echo "mkdir -p $test"
-  mkdir -p $test
-
-  echo "cd $test"
-  cd $test
-
-  # Run test version
-  #
-  echo "Running:   $TESTING_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
-  echo "******************** (TEST) $load *******************" >> $log
-  $TESTING_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load 2>&1| tee -a $log 
-  # Now run current release version if not already there
-  #
-  if [ ! -r $release/starcheck.txt ]
-  then
-    echo "mkdir -p $release"
-    mkdir -p $release
-
-    echo "cd $release"
-    cd $release
-
-    echo "Running: $RELEASE_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
-    echo "**** (RELEASE) $load ****" >> $log
-    env SKA=/proj/sot/ska PERL5LIB= $RELEASE_BIN/starcheck.pl -agasc 1p5 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load  2>&1| tee -a $log
-  fi  
-
-  # Now compare with release version
-
-  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
-  echo "********************* $load ********************" >> $diffs
-  diff $test/starcheck.txt $release/starcheck.txt >> $diffs
-
-  cd $home
+do
+   RunRegression 1p5 fid_CHARACTERIS_JUL01
 done
 
 # Then a bunch of agasc 1.6 loads
@@ -102,54 +119,8 @@ for load in \
     2006/MAR0606/oflsc \
     2006/NOV1306/oflsa \
     2006/AUG0706/oflsb
-  do
-  echo ""
-  echo "***** Running starcheck on load $load *****"
-
-  test=$home/regress/test/$load
-  release=$home/regress/release/$load
-
-  # Make sure we have a clean test directory
-  if [ -d $test ]
-  then
-    echo "rm -r $test"
-    rm -r $test
-  fi
-
-  echo "mkdir -p $test"
-  mkdir -p $test
-
-  echo "cd $test"
-  cd $test
-
-  # Run test version
-  #
-  echo "Running: $home/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
-  echo "******************** (TEST) $load *******************" >> $log
-  $TESTING_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load 2>&1| tee -a $log 
-  # Now run current release version if not already there
-  #
-  if [ ! -r $release/starcheck.txt ]
-  then
-    echo "mkdir -p $release"
-    mkdir -p $release
-
-    echo "cd $release"
-    cd $release
-
-    echo "Running: /proj/sot/ska/perl/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load"
-    echo "**** (RELEASE) $load ****" >> $log
-    env SKA=/proj/sot/ska PERL5LIB= $RELEASE_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_JUL01 -dir $mphome/$load 2>&1| tee -a $log
-  fi  
-
-
-  # Now compare with release version
-
-  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
-  echo "********************* $load ********************" >> $diffs
-  diff $test/starcheck.txt $release/starcheck.txt >> $diffs
-
-  cd $home
+do
+  RunRegression 1p6 fid_CHARACTERIS_JUL01
 done
 
 # Then, a bunch of agasc 1.6 loads with the updated fid characteristics
@@ -161,54 +132,8 @@ for load in \
     2008/MAY0508/oflsa \
     2008/AUG1808/oflsa \
     2008/SEP0108/oflsb
-  do
-  echo ""
-  echo "***** Running starcheck on load $load *****"
-
-  test=$home/regress/test/$load
-  release=$home/regress/release/$load
-
-  # Make sure we have a clean test directory
-  if [ -d $test ]
-  then
-    echo "rm -r $test"
-    rm -r $test
-  fi
-
-  echo "mkdir -p $test"
-  mkdir -p $test
-
-  echo "cd $test"
-  cd $test
-
-  # Run test version
-  #
-  echo "Running: $home/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load"
-  echo "******************** (TEST) $load *******************" >> $log
-  $TESTING_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load 2>&1| tee -a $log 
-  # Now run current release version if not already there
-  #
-  if [ ! -r $release/starcheck.txt ]
-  then
-    echo "mkdir -p $release"
-    mkdir -p $release
-
-    echo "cd $release"
-    cd $release
-
-    echo "Running: /proj/sot/ska/perl/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load"
-    echo "**** (RELEASE) $load ****" >> $log
-    env SKA=/proj/sot/ska PERL5LIB= $RELEASE_BIN/starcheck.pl -agasc 1p6 -fid_char fid_CHARACTERIS_FEB07 -dir $mphome/$load 2>&1| tee -a $log
-  fi  
-
-
-  # Now compare with release version
-
-  echo "diff $test/starcheck.txt $release/starcheck.txt >> $diffs"
-  echo "********************* $load ********************" >> $diffs
-  diff $test/starcheck.txt $release/starcheck.txt >> $diffs
-
-  cd $home
+do
+  RunRegression 1p6 fid_CHARACTERIS_FEB07
 done
 
 
